# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da00937219d4d8aa62a8d0f5cb6994a0d44c4826330fb095dd1b472c0e56da6576804e8c84090fcba16302ebc8f84cf884b5781966bebd8d406aaff7ea16fc7

test:
  secret_key_base: 33ae7518cd6c3ceffceafd9bc7413ec8810600f24a83692b0a3f73b17981cff1dde0089948b1698d8056a55477d6b1883625db3f7c126dd53ea41dd136293dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
